### ISSUE TITLE
Python 3 install fails

### ISSUE THREAD

**Issue by Tirpitz93** [Jaymon/dump#14]
bytes/string conversion issue. seams to be Py3k compatibility issue.

```
Downloading/unpacking dump==0.0.3 (from -r /var/www/haproxy-wi/requirements.txt (line 7))
  Downloading dump-0.0.3.tar.gz
  Running setup.py (path:/tmp/pip-build-uasclc1x/dump/setup.py) egg_info for package dump
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-uasclc1x/dump/setup.py", line 13, in <module>
        version = re.search("^__version__\s*=\s*[\'\"]([^\'\"]+)", f.read(), flags=re.I | re.M).group(1)
      File "/usr/lib/python3.4/re.py", line 166, in search
        return _compile(pattern, flags).search(string)
    TypeError: can't use a string pattern on a bytes-like object
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-uasclc1x/dump/setup.py", line 13, in <module>

    version = re.search("^__version__\s*=\s*[\'\"]([^\'\"]+)", f.read(), flags=re.I | re.M).group(1)

  File "/usr/lib/python3.4/re.py", line 166, in search

    return _compile(pattern, flags).search(string)

TypeError: can't use a string pattern on a bytes-like object

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-uasclc1x/dump
Storing debug log for failure in /root/.pip/pip.log
Unable to install Required Packages, Please check Pip error log and Fix the errors and Rerun the script

```

**Comment by Jaymon** [comment]
From the output, it looks like you're pegged to version 0.0.3 (eg, `dump==0.0.3`), bump the version to 0.0.4 (eg, `dump==0.0.4`) and it should install without problems, the [only thing that really changed](https://github.com/Jaymon/dump/commit/c64f0bce0175a47d507dea9b9fa10b846c75bc1d) is I fixed the setup.py script.
