### ISSUE TITLE
Unable to install dump 

### ISSUE THREAD

**Issue by melina** [Jaymon/dump#15]
Installation of dump is failing with the following error on Debian jessie.

```
sudo pip3 install dump
Downloading/unpacking dump
  Downloading dump-0.0.4.tar.gz
  Running setup.py (path:/tmp/pip-build-chdok_j7/dump/setup.py) egg_info for package dump
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-chdok_j7/dump/setup.py", line 13, in <module>
        version = re.search("^__version__\s*=\s*[\'\"]([^\'\"]+)", f.read(), flags=re.I | re.M).group(1)
      File "/usr/lib/python3.4/re.py", line 166, in search
        return _compile(pattern, flags).search(string)
    TypeError: can't use a string pattern on a bytes-like object
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-chdok_j7/dump/setup.py", line 13, in <module>

    version = re.search("^__version__\s*=\s*[\'\"]([^\'\"]+)", f.read(), flags=re.I | re.M).group(1)

  File "/usr/lib/python3.4/re.py", line 166, in search

    return _compile(pattern, flags).search(string)

TypeError: can't use a string pattern on a bytes-like object
```

Found this similar [issue](https://github.com/Jaymon/dump/issues/14), but the version is already `0.0.4`

Thanks.

**Comment by Jaymon** [comment]
Strange, in an Ubuntu virtual machine I get this:

```
$ python3 --version
Python 3.4.3
$
$ sudo pip3 install dump
Downloading/unpacking dump
  Downloading dump-0.0.4.tar.gz
  Running setup.py (path:/tmp/pip_build_root/dump/setup.py) egg_info for package dump

Installing collected packages: dump
  Running setup.py install for dump

    Installing dump script to /usr/local/bin
Successfully installed dump
Cleaning up...
```

I modified the `setup.py` file a bit more since I suspect it might just be it can't figure out the encoding of `__init__.py` and so it defaults to a bytes object, if you can try installing from source:

    $ sudo pip3 install git+https://github.com/Jaymon/dump#egg=dump

and let me know if that works. If it does work then I'll push it out to pypi.

Thanks :)

**Comment by melina** [comment]
thank you @Jaymon 👍 that worked

I am on `Python 3.4.2`, though.

**Comment by Jaymon** [comment]
Great! I'm glad it worked. I don't think a point release would be that different so I'm going to consider this closed and I'll push a new version to pypi
